language: python
sudo: required
dist: trusty
services:
  - memcached
  - postgresql
  - redis-server

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

addons:
  apt:
    update: true
    packages:
      - libxmlsec1-dev
      - libgeoip-dev
  chrome: stable

env:
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=on
    - SENTRY_SKIP_BACKEND_VALIDATION=1
    - TRAVIS_NODE_VERSION=10.16.3
    - YARN_VERSION="1.17.3"
    - NODE_OPTIONS=--max-old-space-size=4096

matrix:
  include:
    - python: 2.7
      install:
        - 'export PATH=$PATH:~/.bin'
        - nvm install $TRAVIS_NODE_VERSION
        - npm install -g "yarn@${YARN_VERSION}"
        # trusty comes with pyenv-managed 2.7 and 3.6 - we need python3 -> 3.6 on the PATH for pre-commit to install black during 2.7 tests.
        - pyenv global 3.6.3 2.7.14
        - make install-tests
        # reset to system python(s) to avoid surprises.
        - pyenv global system
        - python -m pip install codecov
        - pip freeze
        - |
          CHROME_MAJOR_VERSION="$(dpkg -s google-chrome-stable | sed -nr 's/Version: ([0-9]+).*/\1/p')"
          wget -N "https://chromedriver.storage.googleapis.com/$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION})/chromedriver_linux64.zip" -P ~/
        - unzip ~/chromedriver_linux64.zip -d ~/
        - rm ~/chromedriver_linux64.zip
        - sudo install -m755 ~/chromedriver /usr/local/bin/
      before_script:
        - psql -c 'create database sentry;' -U postgres
      script:
        - make lint
        - py.test --cov . --cov-report="xml:.artifacts/coverage.xml" --junit-xml=".artifacts/junit.xml" --html="artifacts/pytest.html" || exit 1
      after_success:
        - codecov -e TEST_SUITE
      after_failure:
        - dmesg | tail -n 100
      after_script:
        - npm install -g @zeus-ci/cli
        - zeus upload -t "text/xml+xunit" .artifacts/*junit.xml
        - zeus upload -t "text/xml+coverage" .artifacts/*coverage.xml
        - zeus upload -t "text/xml+coverage" .artifacts/coverage/cobertura-coverage.xml
        - zeus upload -t "text/html+pytest" .artifacts/*pytest.html
        - zeus upload -t "text/plain+pycodestyle" .artifacts/*pycodestyle.log
        - zeus upload -t "text/xml+checkstyle" .artifacts/*checkstyle.xml
        - zeus upload -t "application/webpack-stats+json" .artifacts/*webpack-stats.json

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/3b18261a-deb8-11e7-867b-0a580a281404/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
